### ISSUE TITLE
[MAC OS] FATAL Error: No context is current or a function that is not available in the current context was called 

### ISSUE THREAD

**Issue by damn** [klianc09/imguiexample#2]
I copied your example code into my libgdx clojure app:

* getGLVersion returns "2:1:0"
* I also tried to set glsl version to 110, same error.
* It fails at 

```
GL Version  Type: OpenGL
Version: 2:1:0
Vendor: Intel Inc.
Renderer: Intel(R) Iris(TM) Plus Graphics OpenGL Engine
glsl version:  #version 110
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.glBindVertexArray(Native Method)
	at org.lwjgl.opengl.GL30.glBindVertexArray(GL30.java:2283)
	at imgui.gl3.ImGuiImplGl3.createDeviceObjects(ImGuiImplGl3.java:289)
	at imgui.gl3.ImGuiImplGl3.init(ImGuiImplGl3.java:127)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.19/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.19/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.19/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.19/Method.java:566)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
	at game.imgui$eval6577$fn__6578.invoke(imgui.clj:57)
```

My code:
```
(ns game.imgui
  (:require [game.on-create :refer (on-create)])
  (:import org.lwjgl.opengl.GL
           [org.lwjgl.glfw GLFW GLFWErrorCallback]
           imgui.ImGui
           imgui.glfw.ImGuiImplGlfw
           imgui.gl3.ImGuiImplGl3
           [com.badlogic.gdx Gdx]
           com.badlogic.gdx.graphics.glutils.GLVersion
           [com.badlogic.gdx.backends.lwjgl3 Lwjgl3Graphics]))

(on-create

 (let [glversion (.getGLVersion (Gdx/graphics))]
   (println "GL Version " (.getDebugVersionString glversion)))

 (.set (GLFWErrorCallback/createPrint System/err))

 (when-not (GLFW/glfwInit)
   (IllegalStateException. "Unable to initialize GLFW"))

 (def window-handle (.getWindowHandle (.getWindow (Gdx/graphics))))

 (def glsl-version "#version 110")
 (println "glsl version: " glsl-version)

 (GLFW/glfwMakeContextCurrent window-handle)

 (GL/createCapabilities)

 (GLFW/glfwSwapInterval (GLFW/GLFW_TRUE))
 (ImGui/createContext)

 (def imguiglfw (ImGuiImplGlfw.))
 (def imguigl3 (ImGuiImplGl3.))

 (def io (ImGui/getIO))
 (.setIniFilename io "")
 (.addFontDefault (.getFonts io))
 (.build (.getFonts io))

 (.init imguiglfw window-handle true)
 (.init imguigl3 glsl-version) ; TODO breaks.
 )

(defn render []
  (.newFrame imguiglfw)
  (ImGui/newFrame)

  (ImGui/button "I`m a Button!")

  (ImGui/render)
  (.renderDrawData imguigl3 (ImGui/getDrawData))

  ;(GLFW/glfwSwapBuffers window-handle)
  ;(GLFW/glfwPollEvents)
  )

```

I also tried setting these window hints but it does not change anything:
```
 (GLFW/glfwWindowHint GLFW/GLFW_CONTEXT_VERSION_MAJOR 3)
 (GLFW/glfwWindowHint GLFW/GLFW_CONTEXT_VERSION_MINOR 2)
 (GLFW/glfwWindowHint GLFW/GLFW_OPENGL_FORWARD_COMPAT
                      GLFW/GLFW_TRUE)
 (GLFW/glfwWindowHint GLFW/GLFW_OPENGL_PROFILE
                      GLFW/GLFW_OPENGL_CORE_PROFILE)
```

**Comment by klianc09** [comment]
Have you also tried just checking out this repository and running that? Would be a good starting point to verify that works before you start copying it into your projects.

If "GL Version  Type: OpenGL Version: 2:1:0" is true, then "glBindVertexArray" will not be available as it is only available [since version 3.0](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBindVertexArray.xhtml).
Make sure your PC actually supports OpenGL 3.0 and try to get it running in a non-clojure project first (see my first sentence).
